name: Build And Push Docker Images

on:
  pull_request:
    types: [closed]

jobs:
  Build-And-Push-Docker-Images:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Docker Buildx Set Up
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Frontend - Build And Push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: sammulto/dogdates:frontend-git
      - 
        name: Create env file for backend
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_NAME: dogdatesDevDB
          envkey_TOKEN_SCERT: ${{ secrets.TOKEN_SCERT }}
          envkey_SERVER_PORT: 5000
          directory: backend
          file_name: .env
          fail_on_empty: false
      - 
        name: Backend - Build And Push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: sammulto/dogdates:backend-git

